#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0 on Tue Apr  3 16:51:04 2018
#

import wx
import wx.grid

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((800, 600))
        self.window_1 = wx.SplitterWindow(self, wx.ID_ANY)
        self.tree_ctrl_left = wx.TreeCtrl(self.window_1, wx.ID_ANY)
        self.panel_right = wx.Panel(self.window_1, wx.ID_ANY)
        self.panel_command = wx.Panel(self.panel_right, wx.ID_ANY)
        self.button_1 = wx.Button(self.panel_command, wx.ID_ANY, "button_1")
        self.button_2 = wx.Button(self.panel_command, wx.ID_ANY, "button_2")
        self.button_3 = wx.Button(self.panel_command, wx.ID_ANY, "button_3")
        self.grid_grid = wx.grid.Grid(self.panel_right, wx.ID_ANY, size=(1, 1))
        self.text_ctrl_msg = wx.TextCtrl(self, wx.ID_ANY, "")
        
        # Menu Bar
        self.mainframe_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Exit", "")
        self.Bind(wx.EVT_MENU, self.on_menu_exit, id=item.GetId())
        self.mainframe_menubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Merge SummaryReport", "")
        self.Bind(wx.EVT_MENU, self.on_menu_mergesummaryreport, id=item.GetId())
        self.mainframe_menubar.Append(wxglade_tmp_menu, "Database")
        self.SetMenuBar(self.mainframe_menubar)
        # Menu Bar end

        self.__set_properties()
        self.__do_layout()

        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("Tyro Case Management")
        self.grid_grid.CreateGrid(10, 0)
        self.window_1.SetMinimumPaneSize(20)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_main = wx.BoxSizer(wx.VERTICAL)
        sizer_grid = wx.BoxSizer(wx.VERTICAL)
        sizer_command = wx.BoxSizer(wx.HORIZONTAL)
        sizer_command.Add(self.button_1, 0, 0, 0)
        sizer_command.Add(self.button_2, 0, 0, 0)
        sizer_command.Add(self.button_3, 0, 0, 0)
        sizer_command.Add((0, 0), 0, 0, 0)
        self.panel_command.SetSizer(sizer_command)
        sizer_grid.Add(self.panel_command, 0, wx.EXPAND, 0)
        sizer_grid.Add(self.grid_grid, 1, wx.EXPAND, 0)
        self.panel_right.SetSizer(sizer_grid)
        self.window_1.SplitVertically(self.tree_ctrl_left, self.panel_right)
        sizer_main.Add(self.window_1, 1, wx.EXPAND, 0)
        sizer_main.Add(self.text_ctrl_msg, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_main)
        self.Layout()
        self.Centre()
        # end wxGlade

    def on_menu_exit(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'on_menu_exit' not implemented!")
        event.Skip()

    def on_menu_mergesummaryreport(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'on_menu_mergesummaryreport' not implemented!")
        event.Skip()

# end of class MainFrame

class SummaryFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SummaryFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1082, 470))
        self.panel_info = wx.Panel(self, wx.ID_ANY)
        self.panel_command = wx.Panel(self, wx.ID_ANY)
        self.text_ctrl_filepath = wx.TextCtrl(self.panel_command, wx.ID_ANY, "")
        self.button_selectfile = wx.Button(self.panel_command, wx.ID_ANY, "Local")
        self.button_download = wx.Button(self.panel_command, wx.ID_ANY, "Remote")
        self.button_mergefile = wx.Button(self.panel_command, wx.ID_ANY, "Merge")
        self.text_ctrl_msg = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.on_button_select, self.button_selectfile)
        self.Bind(wx.EVT_BUTTON, self.on_button_merge, self.button_mergefile)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SummaryFrame.__set_properties
        self.SetTitle("Merge Summary")
        self.button_download.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SummaryFrame.__do_layout
        sizer_summary = wx.BoxSizer(wx.VERTICAL)
        sizer_command = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        label_1 = wx.StaticText(self.panel_info, wx.ID_ANY, "Total Records :")
        sizer_2.Add(label_1, 0, wx.BOTTOM | wx.LEFT | wx.TOP, 10)
        label_2 = wx.StaticText(self.panel_info, wx.ID_ANY, "NONE")
        sizer_2.Add(label_2, 0, wx.BOTTOM | wx.TOP, 10)
        label_3 = wx.StaticText(self.panel_info, wx.ID_ANY, "Last Record NO :")
        sizer_2.Add(label_3, 0, wx.BOTTOM | wx.LEFT | wx.TOP, 10)
        label_4 = wx.StaticText(self.panel_info, wx.ID_ANY, "NONE")
        sizer_2.Add(label_4, 0, wx.BOTTOM | wx.TOP, 10)
        label_5 = wx.StaticText(self.panel_info, wx.ID_ANY, "Last Record Opendate :")
        sizer_2.Add(label_5, 0, wx.BOTTOM | wx.LEFT | wx.TOP, 10)
        label_6 = wx.StaticText(self.panel_info, wx.ID_ANY, "NONE")
        sizer_2.Add(label_6, 0, wx.BOTTOM | wx.TOP, 10)
        sizer_2.Add((0, 0), 0, 0, 0)
        self.panel_info.SetSizer(sizer_2)
        sizer_summary.Add(self.panel_info, 0, wx.ALL | wx.EXPAND, 0)
        label_file = wx.StaticText(self.panel_command, wx.ID_ANY, "File :", style=wx.ALIGN_CENTER)
        sizer_command.Add(label_file, 0, wx.ALIGN_CENTER | wx.LEFT | wx.RIGHT, 10)
        sizer_command.Add(self.text_ctrl_filepath, 1, wx.ALL | wx.EXPAND, 5)
        sizer_command.Add(self.button_selectfile, 0, wx.BOTTOM | wx.LEFT | wx.TOP, 5)
        sizer_command.Add(self.button_download, 0, wx.BOTTOM | wx.LEFT | wx.TOP, 5)
        sizer_command.Add(self.button_mergefile, 0, wx.ALL, 5)
        self.panel_command.SetSizer(sizer_command)
        sizer_summary.Add(self.panel_command, 0, wx.ALL | wx.EXPAND, 0)
        sizer_summary.Add(self.text_ctrl_msg, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_summary)
        self.Layout()
        self.Centre()
        # end wxGlade

    def on_button_select(self, event):  # wxGlade: SummaryFrame.<event_handler>
        print("Event handler 'on_button_select' not implemented!")
        event.Skip()

    def on_button_merge(self, event):  # wxGlade: SummaryFrame.<event_handler>
        print("Event handler 'on_button_merge' not implemented!")
        event.Skip()

# end of class SummaryFrame

class TCM(wx.App):
    def OnInit(self):
        self.mainframe = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.mainframe)
        self.mainframe.Show()
        return True

# end of class TCM

if __name__ == "__main__":
    app = TCM(0)
    app.MainLoop()
